spring:
  config:
    activate:
      on-profile: "prod"

build-version: "1.0"

cards:
  message: "Welcome to EazyBank cards related PROD APIs"
  contactDetails:
    name: "Alex Arthur - Product Owner"
    email: "alex@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345